name: nix-build installer iso

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v13
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm
      - name: Build Nix flake
        run: |
          nix build -L \
            .#nixosConfigurations.installer-iso.config.system.build.isoImage

      - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: nix-result
          path: ${{ env.UPLOAD_PATH }}
