name: nix-build installer iso

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y curl bzip2
            mkdir -m 0755 /nix && chown aaronlevin /nix
            curl -L https://nixos.org/nix/install | sh
          run: |
            . .nix-profile/etc/profile.d/nix.sh && nix-channel --update && nix build --extra-experimental-features "nix-command flakes" -L \
              .#deploy.nodes.oci-aarm64-1.profiles.system.path

      - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: nix-result
          path: ${{ env.UPLOAD_PATH }}
