name: rpi2 arm7 sd card

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            curl -Lo RELEASE https://raw.githubusercontent.com/nixbuild/nix-quick-install-action/master/RELEASE

            export RELEASE_FILE="RELEASE"
            export NIX_VERSION="2.9.1"
            export NIX_CONF="experimental-features = nix-command flakes"
            export NIX_ON_TMPFS="false"

            curl -L https://raw.githubusercontent.com/nixbuild/nix-quick-install-action/master/nix-quick-install.sh | bash

            nix build -L \
              .#images.rpi2
      
      # - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: nix-result
      #     path: ${{ env.UPLOAD_PATH }}
